import type { Metadata } from "next";
import { Open_Sans, Mulish } from "next/font/google";
import "./globals.css";
import React from "react";
import NavBar from "@/NavBar";
import FooterSection from "@/components/Footer";


const openSans = Open_Sans({
    subsets: ["latin"],
    variable: "--font-open-sans",
    display: "swap",
});

const mulish = Mulish({
    subsets: ["latin"],
    variable: "--font-mulish",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${openSans.variable} ${mulish.variable} antialiased`}>
        <NavBar/>
        {children}
        <FooterSection/>
        </body>
        </html>
    );
}
