import type {Metadata} from "next";
import {Mulish, Open_Sans} from "next/font/google";
import "./globals.css";
import React from "react";
import ReactQueryProvider from "@/Provider/ReactQueryProvider";
import {Toaster} from "sonner";
import Script from "next/dist/client/script";


const openSans = Open_Sans({
    subsets: ["latin"],
    variable: "--font-open-sans",
    display: "swap",
});

const mulish = Mulish({
    subsets: ["latin"],
    variable: "--font-mulish",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${openSans.variable} ${mulish.variable} antialiased`}>
        <Toaster
            richColors
            position="top-right"
            duration={5000}
        />
        <ReactQueryProvider>
            {children}
        </ReactQueryProvider>
        </body>
        </html>
    );
}
